### ISSUE TITLE
Please add Mauritius - MU

### ISSUE THREAD

**Issue by TP75** [nextcloud/privacy#263] opened 2019-11-22 15:19 UTC
Please add

- https://en.wikipedia.org/wiki/Mauritius
- https://en.wikipedia.org/wiki/ISO_3166-2:MU 
 
if I understand the below forum request correctly.

https://help.nextcloud.com/t/my-country-location-is-unavailable/64780

**Comment by georgehrke** [comment] 2019-11-28 14:11
Duplicate of #241

**Closed by georgehrke** 2019-11-28 14:11 UTC
