### ISSUE TITLE
Country

### ISSUE THREAD

**Issue by chummumm** [nextcloud/privacy#247] opened 2019-10-24 03:22 UTC
Hello, taiwan isn't a country, please fix it.
![IMG_20191024_155925](https://user-images.githubusercontent.com/50511147/67465569-fd234900-f677-11e9-8daf-4f2b4a4fd8cd.jpg)

**Comment by dguhl** [comment] 2019-10-26 09:38
We do not maintain these names within this project. Please open an issue in the project punic/punic, as that is the library NextCloud uses for country names and other locale-relevant information over its nextcloud/3rdparty project.

**Comment by chummumm** [comment] 2019-10-26 10:02
ok, Thanks

**Comment by kesselb** [comment] 2019-10-26 13:06
> We do not maintain these names within this project. Please open an issue in the project punic/punic, as that is the library NextCloud uses for country names and other locale-relevant information over its nextcloud/3rdparty project.

I think you are wrong. https://github.com/nextcloud/privacy/blob/76f41b4f1c621c46a0d1249b03bf409ff018fb70/src/nameProvider.js#L162

@chummumm you should be able to change the translation via transifex: https://www.transifex.com/nextcloud/nextcloud/

**Comment by dguhl** [comment] 2019-10-26 13:39
> 
> I think you are wrong.
> https://github.com/nextcloud/privacy/blob/76f41b4f1c621c46a0d1249b03bf409ff018fb70/src/nameProvider.js#L162

I think I'm not. 🤷‍♂ 
https://github.com/nextcloud/3rdparty/blob/master/punic/punic/code/data/en/territories.json

**Comment by jospoortvliet** [comment] 2019-10-26 13:42
@chummumm We can solve this easily in the translations. There is a Chinese Taiwan translation and a Chinese mainland translation. The former can follow the convention of the Taiwan people, the second can follow the Chinese government policy that Taiwan is a province.

**Comment by chummumm** [comment] 2019-10-26 16:32
> @chummumm We can solve this easily in the translations. There is a Chinese Taiwan translation and a Chinese mainland translation. The former can follow the convention of the Taiwan people, the second can follow the Chinese government policy that Taiwan is a province.

Taiwan is always a province of China.
Maybe CLDR made a mistake, so I want the team of nextcloud can give an issue to them, then fix it.
Taiwan isn't a country.

**Comment by dguhl** [comment] 2019-10-26 16:48
I believe the people of Taiwan would take offense in a translation in which their place is named a province of China and that @jospoortvliet suggests the best solution for this problem.

**Comment by kesselb** [comment] 2019-10-26 16:59
> Maybe CLDR made a mistake,

https://unicode-org.atlassian.net/browse/CLDR-11743

> Taiwan(Province of China)?

Nextcloud use transifex to manage translations. You can use your GitHub account to join and fix the wrong string here: https://www.transifex.com/nextcloud/nextcloud/viewstrings/#zh_CN/privacy/166313704?q=text%3ATaiwan I guess it's much easier for a native speaker. Thanks :+1:

**Comment by chummumm** [comment] 2019-10-26 16:59
> I believe the people of Taiwan would take offense in a translation in which their place is named a province of China and that @jospoortvliet suggests the best solution for this problem.

You can fix this problem like this, but a lot of people of Taiwan think they are Chinese.
Ummmm, I like the project of yours.
![IMG_20191027_005823](https://user-images.githubusercontent.com/50511147/67623168-fef63380-f854-11e9-893b-f7e8250ccd27.jpg)

**Comment by chummumm** [comment] 2019-10-26 17:04
> > Maybe CLDR made a mistake,
> 
> https://unicode-org.atlassian.net/browse/CLDR-11743
> 
> > Taiwan(Province of China)?
> 
> Nextcloud use transifex to manage translations. You can use your GitHub account to join and fix the wrong string here: https://www.transifex.com/nextcloud/nextcloud/viewstrings/#zh_CN/privacy/166313704?q=text%3ATaiwan I guess it's much easier for a native speaker. Thanks

Thanks, I will do this several months later.

**Comment by georgehrke** [comment] 2019-11-28 14:11
Duplicate of #241

**Closed by georgehrke** 2019-11-28 14:11 UTC
