### ISSUE TITLE
Bug Version 1.3.0 - Box encryption activated

### ISSUE THREAD

**Issue by hume1991** [nextcloud/privacy#507] opened 2020-09-02 13:07 UTC
If the box: server-side encryption is activated, this is accepted at the moment, but the box is deactivated again after the next change.

Best regards

Christian Huml

**Comment by georgehrke** [comment] 2020-09-02 13:13
Duplicate of https://github.com/nextcloud/privacy/issues/427

**Closed by georgehrke** 2020-09-02 13:13 UTC
